; (rule
;   (target opentrace)
;   (action
;     (with-stdout-to opentrace (run echo hello))))

(library
 (name shelter)
 (public_name shelter)
 (preprocess
  (pps ppx_repr))
 (libraries
  astring
  cmdliner
  irmin
  cid
  void
  zfs
  shl
  linenoise
  irmin-git.unix
  terminal))

(rule
 (targets raw_flags.ml)
 (action
  (run ./include/discover.exe)))
